### ISSUE TITLE
Missing chunk upload config in doc

### ISSUE THREAD

**Issue by bastos71** [jargoud/laravel-backpack-dropzone#3]
Could we add this piece of config for a CRUD field to enable by default the chunk upload ? 🙏

```php
'config' => [
    'chunkSize' => 1024 * 1024 * 2, // for 2Mo
    'chunking' => true
],
```

**Comment by jargoud** [comment]
Done in [release 2.0.1](https://github.com/jargoud/laravel-backpack-dropzone/releases/tag/2.0.1). Thanks!
