### ISSUE TITLE
support backpack 6

### ISSUE THREAD

**Issue by TiesTheunissen** [jargoud/laravel-backpack-dropzone#5]
i currently it saids that only packpack 5 is supported while 6 is already out. can we update it to packpack 6?

**Comment by jargoud** [comment]
Hello,

Indeed that will be needed :)

I'll try to find some time to support Backpack 6.

Jeremy

**Comment by jargoud** [comment]
Hello @TiesTheunissen

With some delay, @WSauvan contributed and a new release 4.0.0 has been published, with support for Laravel 11 and Backpack 6!
